### ISSUE TITLE
添加设备详细列表

### ISSUE THREAD

**Issue by thun888** [thun888/mirouter-ui#1]
在设备数量过多时，路由器会把一些设备集合为Others，需要用另外一个API才能获取各个设备的信息

**Comment by HADB** [comment]
这个问题有解决吗？我用最新版的看起来还是只能拿到前9个设备，其他设备会聚合成Others，从设备列表点进去就提示错误：该设备（如智能插座）不支持此功能😢

**Comment by thun888** [comment]
目前获取设备信息有用到两个接口。一个能获取大部分基本信息，包括网络活动频繁的设备的网络信息。另一个只能获取全部的设备的部分信息，不包括网络信息。
打开页面的时候通过第一个接口获取不到就报错，但即便报错也有获取到部分信息，那个就是第二个接口获取到的。总的来说，没有办法┐(´-｀)┌

**Comment by HADB** [comment]
@thun888 感谢回复，我上次研究了下确实结论也是一样的，好蛋疼……
