### ISSUE TITLE
关于docker启动的问题

### ISSUE THREAD

**Issue by MuXia-0326** [thun888/mirouter-ui#14]
使用docker启动的新版本，没办法获取数据
![image](https://github.com/Mirouterui/mirouter-ui/assets/63834850/ef947ba8-3e49-4aae-8656-85eaeef6f497)

**Comment by thun888** [comment]
请提供运行日志
>  docker logs -f -t  mirouter-ui

**Comment by thun888** [comment]
不用了，还是把static删了就行

**Comment by MuXia-0326** [comment]
可以了，感谢作者
