### ISSUE TITLE
bug 历史记录cpu占用率为0，路由器状态cpu占用大概1-5%之间波动

### ISSUE THREAD

**Issue by LongMan98** [thun888/mirouter-ui#18]
![捕获](https://github.com/Mirouterui/mirouter-ui/assets/60247620/1d35c3b6-f90a-4f03-823f-b8698fc7bbdc)
![捕获1](https://github.com/Mirouterui/mirouter-ui/assets/60247620/8e81ef8b-96bc-4ada-beec-a345ef88d516)

**Comment by thun888** [comment]
![image](https://github.com/Mirouterui/mirouter-ui/assets/63234268/13c75916-f6d3-40cd-8288-85ca6cec1081)
复制一下网络请求来看看

**Comment by LongMan98** [comment]
[gethistoryrouternum=0.txt](https://github.com/Mirouterui/mirouter-ui/files/14480186/gethistoryrouternum.0.txt)

**Comment by thun888** [comment]
试下这个版本
https://pan.hzchu.top/s/9ehq

**Comment by LongMan98** [comment]
我是部署在docker上的😂

**Comment by thun888** [comment]
其实我想让你先测试下的😂docker的话可以拉取dev分支试试

**Comment by LongMan98** [comment]
更新1.3.2 bug还在

**Comment by thun888** [comment]
![image](https://github.com/Mirouterui/mirouter-ui/assets/63234268/e30cc3bb-14a0-4062-b0f2-6d55623f5b1c)
![image](https://github.com/Mirouterui/mirouter-ui/assets/63234268/f74efc9e-703b-406d-98af-4f29516ef66b)
我在本地无法复现这个问题🫥
