### ISSUE TITLE
ipv6地址信息能获取到吗

### ISSUE THREAD

**Issue by NickNameIsNull** [thun888/mirouter-ui#33]
小米BE7000
路由器启用了了IPV6>Native；
请问路由器本身的接口，有哪个接口可以获取到IPV6分配的IP地址信息。

**Comment by thun888** [comment]
似乎没有，无论是网页端还是app都看不到

**Comment by thun888** [comment]
你好，尝试访问以下链接并提供返回内容

- http://{ip}/cgi-bin/luci/;stok={stok}/api/xqnetwork/ipv6_status
- http://{ip}/cgi-bin/luci/;stok={stok}/api/xqnetwork/get_lan6_v2

与 [局域网，ipv6] 有关的接口只有这2个，需要实机测试才能确定是否有效

**Comment by NickNameIsNull** [comment]
好的，我在真机上尝试下。
PS：路由器提供的API接口这块有详细的资料文档吗，如果有的话是否方便提供一下呢。
目前我是通过浏览器的network获取到的接口信息，感觉不太全面。

**Comment by thun888** [comment]
我也不是内部开发人员，这个真没有🤣
不过我反汇编了下BE7000的lua，可以参考（_u后缀的）
[api_u.zip](https://github.com/user-attachments/files/16373514/api_u.zip)

**Comment by NickNameIsNull** [comment]
非常感谢您提供的信息。
