### ISSUE TITLE
[功能] 能否将多个路由器信息整合进一个容器中

### ISSUE THREAD

**Issue by SeanChengN** [thun888/mirouter-ui#4]
每个docker容器只能管理一个路由器，能否在一个容器中添加多个配置来统一管理路由器。

**Comment by thun888** [comment]
以后支持

**Comment by thun888** [comment]
赶了个版本，试试(･ิϖ･ิ)っ

**Comment by SeanChengN** [comment]
> 赶了个版本，试试(･ิϖ･ิ)っ

新格式研究了一会儿弄明白了，功能正常。
另外发现mesh模式和中继模式的子路由，只能看到CPU使用率和内存使用率，下载速度之类的无效，路由器后台也没有，估计这模式就是这样

**Comment by thun888** [comment]
这个时候速度信息都是交给主路由统计的
